services:
  # nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"

  # mysql
  db:
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysqldata:



  # docker compose up
  # docker compose up -d
  # docker compose ps
  # docker exec -it {container} sh
  # docker compose up -f {file.yaml} up --env-file ./{file}
  # docker compose exec app composer install